#pragma kernel Main
#include "Includes/Math.hlsl"

RWTexture2D<float> _Result;

int _TextureSize;
int _NumOutScatteringSteps;

float _AtmosphereRadius; // normalized: (1 + atmosphereScale)
float _DensityFalloff;

float DensityAtPoint(float2 position)
{
    float planetRadius = 1;
    float heightAboveSurface = length(position) - planetRadius;
    float height01 = heightAboveSurface / (_AtmosphereRadius - planetRadius);
    return exp(-height01 * _DensityFalloff) * (1 - height01);
}

[numthreads(8, 8, 1)]
void Main(uint2 id : SV_DispatchThreadID)
{
    float2 uv = id / (float)_TextureSize;
    float height01 = uv.y;

    float y = -2 * uv.x + 1;
    float x = sin(acos(y));
    float2 dir = float2(x, y);

    float2 inPoint = float2(0, lerp(1, _AtmosphereRadius, height01));
    float dstThroughAtmosphere = RaySphere(0, _AtmosphereRadius, float3(inPoint, 0), float3(dir, 0)).y;

    inPoint += dir * 0.0001;

    float stepSize = dstThroughAtmosphere / (_NumOutScatteringSteps - 1);
    float outScattering = 0;

    for (int i = 0; i < _NumOutScatteringSteps; i++)
    {
        outScattering += DensityAtPoint(inPoint) * stepSize;
        inPoint += dir * stepSize;
    }

    _Result[id.xy] = outScattering;
}
