using UnityEngine;

public sealed record PrecipitationDto(
    bool RenderPrecipitation,
    float Intensity,
    float StormThreshold,
    float StormSoftness,
    float MaxOpacity,
    int ViewSteps,
    float MaxDistance,
    int MinViewSteps,
    float StepScaleNearAltitude,
    float StepScaleFarAltitude,
    float BottomAltitude,
    float CloudBaseOverlap,
    float BottomFeather,
    float TopFeather,
    float CurtainScale,
    float WindSlant,
    float FallSpeed,
    bool RenderLocalParticles,
    float LocalParticleRadius,
    float LocalParticleVerticalRange,
    float LocalMaxCameraAltitude,
    PrecipitationController.WeatherParticleProof ParticleProof,
    int DustParticleCount,
    float DustBaseDensity,
    float DustStormDensity,
    float DustOpacity,
    float DustSize,
    float DustStreakLength,
    float DustTurbulence,
    Color DustColor,
    int SnowParticleCount,
    float SnowParticleOpacity,
    float SnowFallSpeed,
    float SnowThreshold,
    float SnowSize,
    float SnowTemperatureCelsius,
    float SnowTemperatureBlendCelsius,
    Color SnowColor,
    int RainParticleCount,
    float RainOpacity,
    float RainStreakWidth,
    float RainStreakLength,
    float RainThreshold,
    Color RainColor,
    Color StormRainColor,
    PrecipitationController.DebugView DebugMode,
    float DebugDotMinRadius,
    float DebugDotMaxRadius,
    float DebugDotOpacity)
{
    public static PrecipitationDto From(PrecipitationController c) => new(
        c.RenderPrecipitation,
        c.Intensity,
        c.StormThreshold,
        c.StormSoftness,
        c.MaxOpacity,
        c.ViewSteps,
        c.MaxDistance,
        c.MinViewSteps,
        c.StepScaleNearAltitude,
        c.StepScaleFarAltitude,
        c.BottomAltitude,
        c.CloudBaseOverlap,
        c.BottomFeather,
        c.TopFeather,
        c.CurtainScale,
        c.WindSlant,
        c.FallSpeed,
        c.RenderLocalParticles,
        c.LocalParticleRadius,
        c.LocalParticleVerticalRange,
        c.LocalMaxCameraAltitude,
        c.ParticleProof,
        c.DustParticleCount,
        c.DustBaseDensity,
        c.DustStormDensity,
        c.DustOpacity,
        c.DustSize,
        c.DustStreakLength,
        c.DustTurbulence,
        c.DustColor,
        c.SnowParticleCount,
        c.SnowParticleOpacity,
        c.SnowFallSpeed,
        c.SnowThreshold,
        c.SnowSize,
        c.SnowTemperatureCelsius,
        c.SnowTemperatureBlendCelsius,
        c.SnowColor,
        c.RainParticleCount,
        c.RainOpacity,
        c.RainStreakWidth,
        c.RainStreakLength,
        c.RainThreshold,
        c.RainColor,
        c.StormRainColor,
        c.DebugMode,
        c.DebugDotMinRadius,
        c.DebugDotMaxRadius,
        c.DebugDotOpacity);
}
