using UnityEngine;

public sealed record WaterDto(
    Color ShallowBaseColor,
    Color DeepBaseColor,
    Color FoamColor,
    float ReferenceRadius,
    float ShallowDepth,
    float DeepDepth,
    float ShoreFoamDepth,
    float ShoreRange,
    float EdgeFadeStartMeters,
    float EdgeFadeEndMeters,
    float OceanEdgeFadeEndMeters,
    float WaveAmplitude,
    float WaveScale,
    float WaveSpeed,
    float WaveNormalStrength,
    float SwellAmplitude,
    float SwellWavelength,
    float MotionStrength,
    float SunGlitterIntensity,
    float SunGlitterPower,
    float ShoreFoamIntensity,
    float WhitecapIntensity,
    float Alpha,
    float ShallowColorBlend,
    float DeepColorBlend,
    float ShallowAlphaFactor,
    float ShallowAlphaMin,
    float DeepAlphaMin,
    float LakeFreezeStartTemperature01,
    float LakeFreezeCompleteTemperature01,
    float OceanFreezeStartTemperature01,
    float OceanFreezeCompleteTemperature01,
    float IceOpacity,
    float IceRoughness,
    float IceNormalStrength,
    float IceBreakupScale,
    float RefractionStrength,
    float CausticIntensity,
    float CausticDepth,
    float CausticContrast,
    float CausticPrismStrength,
    float UnderwaterNightScale,
    float UnderwaterShaftIntensity)
{
    public static WaterDto From(WaterSettings src)
    {
        if (src == null) return null;
        return new WaterDto(
            src.ShallowBaseColor,
            src.DeepBaseColor,
            src.FoamColor,
            src.ReferenceRadius,
            src.ShallowDepth,
            src.DeepDepth,
            src.ShoreFoamDepth,
            src.ShoreRange,
            src.EdgeFadeStartMeters,
            src.EdgeFadeEndMeters,
            src.OceanEdgeFadeEndMeters,
            src.WaveAmplitude,
            src.WaveScale,
            src.WaveSpeed,
            src.WaveNormalStrength,
            src.SwellAmplitude,
            src.SwellWavelength,
            src.MotionStrength,
            src.SunGlitterIntensity,
            src.SunGlitterPower,
            src.ShoreFoamIntensity,
            src.WhitecapIntensity,
            src.Alpha,
            src.ShallowColorBlend,
            src.DeepColorBlend,
            src.ShallowAlphaFactor,
            src.ShallowAlphaMin,
            src.DeepAlphaMin,
            src.LakeFreezeStartTemperature01,
            src.LakeFreezeCompleteTemperature01,
            src.OceanFreezeStartTemperature01,
            src.OceanFreezeCompleteTemperature01,
            src.IceOpacity,
            src.IceRoughness,
            src.IceNormalStrength,
            src.IceBreakupScale,
            src.RefractionStrength,
            src.CausticIntensity,
            src.CausticDepth,
            src.CausticContrast,
            src.CausticPrismStrength,
            src.UnderwaterNightScale,
            src.UnderwaterShaftIntensity);
    }

    /// <summary>Authored distances are relative to <see cref="ReferenceRadius"/>; scale them for this planet.</summary>
    public float DistanceScale(float planetRadius) =>
        Mathf.Max(planetRadius / Mathf.Max(ReferenceRadius, 0.0001f), 0.0001f);
}
