using UnityEngine;

public sealed record AtmosphereDto(
    float AtmosphereScale,
    int ViewSteps,
    int SunSteps,
    Vector3 RayleighScattering,
    float RayleighScaleHeight,
    float MieScattering,
    float MieScaleHeight,
    float MieAnisotropy,
    float TerrainClarityDistance,
    float TerrainAtmosphereDistance,
    float SunIntensity,
    float SunDiscSize,
    float SunDiscBlend,
    float SunDiscIntensity,
    float SunAureoleStrength,
    float SunAureolePower,
    bool EnableLightShafts,
    int LightShaftSamples,
    float LightShaftStrength,
    float LightShaftDensity,
    float LightShaftDecay,
    float LightShaftWeight,
    float LightShaftExposure,
    float LightShaftThreshold,
    int BakeTextureSize,
    int BakeSteps,
    int DebugMode)
{
    public static AtmosphereDto From(AtmosphereSettings src) => new(
        src.AtmosphereScale,
        src.ViewSteps,
        src.SunSteps,
        src.RayleighScattering,
        src.RayleighScaleHeight,
        src.MieScattering,
        src.MieScaleHeight,
        src.MieAnisotropy,
        src.TerrainClarityDistance,
        src.TerrainAtmosphereDistance,
        src.SunIntensity,
        src.SunDiscSize,
        src.SunDiscBlend,
        src.SunDiscIntensity,
        src.SunAureoleStrength,
        src.SunAureolePower,
        src.EnableLightShafts,
        src.LightShaftSamples,
        src.LightShaftStrength,
        src.LightShaftDensity,
        src.LightShaftDecay,
        src.LightShaftWeight,
        src.LightShaftExposure,
        src.LightShaftThreshold,
        src.BakeTextureSize,
        src.BakeSteps,
        src.DebugMode);
}
